function ivOpen(x1, x2) { return `x ∈ (${M(x1)}, ${M(x2)})`; }
function ivClosed(x1, x2) { return `x ∈ ⟨${M(x1)}, ${M(x2)}⟩`; }
function ivOutOpen(x1, x2) { return `x ∈ (−∞, ${M(x1)}) ∪ (${M(x2)}, +∞)`; }
function ivOutClosed(x1, x2) { return `x ∈ (−∞, ${M(x1)}⟩ ∪ ⟨${M(x2)}, +∞)`; }
const G5 = [
    () => { const { a, x1, x2, b, c } = mkRoots(); const strict = Math.random() < 0.5; const sign = pick([">", "<"]); const op = strict ? sign : sign + "="; const up = a > 0; const outside = (sign === ">") === up; const good = outside ? (strict ? ivOutOpen(x1, x2) : ivOutClosed(x1, x2)) : (strict ? ivOpen(x1, x2) : ivClosed(x1, x2)); const opts = shuffle([ivOpen(x1, x2), ivClosed(x1, x2), ivOutOpen(x1, x2), ivOutClosed(x1, x2)]); return { q: "Rozwiąż nierówność.", expr: `${quad(a, b, c)} ${op === ">=" ? "≥" : op === "<=" ? "≤" : op} 0`, type: "choice", options: opts, ans: good, sol: `Miejsca zerowe: ${M(x1)} i ${M(x2)}, a = ${M(a)} (ramiona ${up ? "w górę" : "w dół"}).\nSzukamy argumentów, dla których parabola leży ${sign === ">" ? "nad" : "pod"} osią OX ⇒ ${outside ? "przedziały zewnętrzne" : "przedział między miejscami zerowymi"}.\n${strict ? "Nierówność ostra ⇒ końce wyłączone." : "Nierówność nieostra ⇒ końce należą do rozwiązania."}\nOdpowiedź: ${good}` }; },
    () => { let a, b, c, d; do {
        a = RNZ(-3, 3);
        b = R(-5, 5);
        c = R(-6, 6);
        d = b * b - 4 * a * c;
    } while (d >= 0); const sign = pick([">", "<"]), up = a > 0, always = (sign === ">") === up; return { q: "Rozwiąż nierówność.", expr: `${quad(a, b, c)} ${sign} 0`, type: "choice", options: ["x ∈ ℝ", "∅ (brak rozwiązań)", "x ∈ (0, +∞)", "x ∈ (−∞, 0)"], ans: always ? "x ∈ ℝ" : "∅ (brak rozwiązań)", sol: `Δ = ${M(d)} < 0, więc parabola nie przecina osi OX i leży w całości ${up ? "nad" : "pod"} nią.\nNierówność ${sign} 0 jest więc ${always ? "spełniona dla każdego x ∈ ℝ" : "sprzeczna — brak rozwiązań"}.` }; },
    () => { let x1 = R(-5, 3), x2 = x1 + R(2, 6); const b = -(x1 + x2), c = x1 * x2, count = x2 - x1 - 1; return { q: "Ile liczb całkowitych spełnia tę nierówność?", expr: `${quad(1, b, c)} < 0`, type: "input", ans: count, sol: `Miejsca zerowe: ${M(x1)}, ${M(x2)}; a = 1 > 0, więc rozwiązaniem jest (${M(x1)}, ${M(x2)}).\nLiczby całkowite ostro między nimi: od ${M(x1 + 1)} do ${M(x2 - 1)}, czyli ${count}.` }; },
    () => { const { x1, x2 } = mkRoots(); const A = 1; const bb = -A * (x1 + x2), cc = A * x1 * x2; const good = ivOutClosed(x1, x2); const opts = shuffle([good, ivClosed(x1, x2), ivOutOpen(x1, x2), "x ∈ ℝ"]); return { q: "Wyznacz dziedzinę funkcji.", expr: `g(x) = √(${quad(A, bb, cc)})`, type: "choice", options: opts, ans: good, sol: `Warunek: ${quad(A, bb, cc)} ≥ 0. Miejsca zerowe: ${M(x1)}, ${M(x2)}, a = ${A} > 0.\nWyrażenie jest nieujemne poza przedziałem między pierwiastkami (z końcami): ${good}.` }; },
    () => { const r = RNZ(-4, 4), b = -2 * r, c = r * r, sign = pick(["≥", ">"]); const ans = sign === "≥" ? "x ∈ ℝ" : `x ∈ ℝ \\ {${M(r)}}`; return { q: "Rozwiąż nierówność.", expr: `${quad(1, b, c)} ${sign} 0`, type: "choice", options: shuffle(["x ∈ ℝ", `x ∈ ℝ \\ {${M(r)}}`, `x = ${M(r)}`, "∅ (brak rozwiązań)"]), ans, sol: `${quad(1, b, c)} = (x ${r > 0 ? "− " + r : "+ " + Math.abs(r)})² ≥ 0 dla każdego x.\n${sign === "≥" ? "Nierówność nieostra jest więc spełniona zawsze." : `Nierówność ostra wyklucza tylko punkt, w którym kwadrat jest zerem: x = ${M(r)}.`}` }; },
    () => { let x1 = R(-5, 2), x2 = x1 + R(2, 5); const b = -(x1 + x2), c = x1 * x2, k = R(x1 + 1, x2 - 1); return { q: `Czy liczba ${M(k)} spełnia nierówność? Wpisz 1 (tak) lub 0 (nie).`, expr: `${quad(1, b, c)} > 0`, type: "input", ans: 0, sol: `Rozwiązaniem nierówności jest (−∞, ${M(x1)}) ∪ (${M(x2)}, +∞). Liczba ${M(k)} leży między pierwiastkami, więc wartość trójmianu jest tam ujemna — nierówność nie jest spełniona.` }; },
];
const G6 = [
    () => { const { a, p, q, b, c } = mkPQd(); const good = a > 0 ? `⟨${M(q)}, +∞)` : `(−∞, ${M(q)}⟩`; const opts = shuffle(uniq([`⟨${M(q)}, +∞)`, `(−∞, ${M(q)}⟩`, `⟨${M(p)}, +∞)`, "ℝ"])); return { q: "Wyznacz zbiór wartości funkcji.", expr: `f(x) = ${quad(a, b, c)}`, type: "choice", options: opts, ans: good, sol: `Wierzchołek: (${M(p)}, ${M(q)}), a = ${M(a)}.\n${a > 0 ? "Ramiona w górę ⇒ wartości od q w górę" : "Ramiona w dół ⇒ wartości od −∞ do q"}: ZW = ${good}.` }; },
    () => { const { a, p, q, b, c } = mkPQd(); const good = a > 0 ? `⟨${M(p)}, +∞)` : `(−∞, ${M(p)}⟩`; const opts = shuffle(uniq([`⟨${M(p)}, +∞)`, `(−∞, ${M(p)}⟩`, `⟨${M(q)}, +∞)`, `(−∞, ${M(q)}⟩`])); return { q: "W jakim przedziale funkcja jest rosnąca?", expr: `f(x) = ${quad(a, b, c)}`, type: "choice", options: opts, ans: good, sol: `Wierzchołek ma p = ${M(p)}, a = ${M(a)}.\n${a > 0 ? "Dla a > 0 funkcja maleje na (−∞, p⟩ i rośnie na ⟨p, +∞)." : "Dla a < 0 funkcja rośnie na (−∞, p⟩ i maleje na ⟨p, +∞)."}\nOdpowiedź: ${good}` }; },
    () => { const { a, p, q, b, c } = mkPQ(); const m = p - R(1, 4), n = p + R(1, 4); const f = (x) => a * x * x + b * x + c; const vals = [f(m), f(n), f(p)], wantMax = Math.random() < 0.5, ans = wantMax ? Math.max(...vals) : Math.min(...vals); return { q: `Wyznacz ${wantMax ? "największą" : "najmniejszą"} wartość funkcji w przedziale ⟨${M(m)}, ${M(n)}⟩.`, expr: `f(x) = ${quad(a, b, c)}`, type: "input", ans, sol: `Wierzchołek p = ${M(p)} należy do przedziału, więc porównujemy trzy wartości:\nf(${M(m)}) = ${M(f(m))}, f(${M(p)}) = ${M(q)}, f(${M(n)}) = ${M(f(n))}.\n${wantMax ? "Największa" : "Najmniejsza"} z nich to ${M(ans)}.` }; },
    () => { const { a, p, q, b, c } = mkPQ(); const m = p + R(1, 3), n = m + R(1, 4); const f = (x) => a * x * x + b * x + c, wantMax = Math.random() < 0.5, ans = wantMax ? Math.max(f(m), f(n)) : Math.min(f(m), f(n)); return { q: `Wyznacz ${wantMax ? "największą" : "najmniejszą"} wartość funkcji w przedziale ⟨${M(m)}, ${M(n)}⟩.`, expr: `f(x) = ${quad(a, b, c)}`, type: "input", ans, sol: `Wierzchołek p = ${M(p)} NIE należy do ⟨${M(m)}, ${M(n)}⟩, więc funkcja jest tam monotoniczna — wartości skrajne przyjmuje na końcach:\nf(${M(m)}) = ${M(f(m))}, f(${M(n)}) = ${M(f(n))} ⇒ ${M(ans)}.` }; },
    () => { const half = R(3, 12), L = 4 * half; return { q: `Obwód prostokąta wynosi ${L}. Jakie jest jego największe możliwe pole?`, expr: `2(a + b) = ${L}`, type: "input", ans: half * half, sol: `b = ${L / 2} − a, więc P(a) = a(${L / 2} − a) = −a² + ${L / 2}a.\nTo funkcja kwadratowa o a < 0, maksimum w wierzchołku: a = ${L / 4}.\nPₘₐₓ = ${L / 4} · ${L / 4} = ${half * half} (kwadrat).` }; },
    () => { const h = R(3, 14), S = 2 * h; return { q: `Suma dwóch liczb rzeczywistych jest równa ${S}. Jaki jest ich największy możliwy iloczyn?`, expr: `x + y = ${S}`, type: "input", ans: h * h, sol: `y = ${S} − x, więc I(x) = x(${S} − x) = −x² + ${S}x.\nWierzchołek: x = ${S}/2 = ${h}, stąd Iₘₐₓ = ${h}·${h} = ${h * h}.` }; },
    () => { const { a, p, q, b, c } = mkPQ(); const k = q + (a > 0 ? -RNZ(1, 5) : RNZ(1, 5)); return { q: `Ile rozwiązań ma równanie f(x) = ${M(k)}?`, expr: `f(x) = ${quad(a, b, c)}`, type: "input", ans: 0, sol: `Zbiór wartości funkcji to ${a > 0 ? `⟨${M(q)}, +∞)` : `(−∞, ${M(q)}⟩`}, a liczba ${M(k)} do niego nie należy. Równanie nie ma rozwiązań.` }; },
];
