const G7 = [
    () => { const b = 2 * RNZ(-4, 4), bound = (b * b) / 4, good = `m < ${M(bound)}`; const opts = shuffle([good, `m > ${M(bound)}`, `m ≤ ${M(bound)}`, `m = ${M(bound)}`]); return { q: "Dla jakich wartości parametru m równanie ma dwa różne pierwiastki rzeczywiste?", expr: `x² ${b > 0 ? "+ " + b : "− " + Math.abs(b)}x + m = 0`, type: "choice", options: opts, ans: good, sol: `Δ = ${b * b} − 4m > 0 ⇒ 4m < ${b * b} ⇒ m < ${M(bound)}.` }; },
    () => { const b = RNZ(-6, 6), k = RNZ(-6, 6), good = `m < ${M(-k)}`; const opts = shuffle([good, `m > ${M(-k)}`, `m < ${M(k)}`, `m > ${M(k)}`]); return { q: "Dla jakich m równanie ma dwa pierwiastki o różnych znakach?", expr: `x² ${b > 0 ? "+ " + b : "− " + Math.abs(b)}x + (m ${k >= 0 ? "+ " + k : "− " + Math.abs(k)}) = 0`, type: "choice", options: opts, ans: good, sol: `Pierwiastki mają różne znaki ⇔ x₁x₂ < 0 ⇔ c/a < 0.\nm ${k >= 0 ? "+ " + k : "− " + Math.abs(k)} < 0 ⇒ m < ${M(-k)}.\n(Warunek Δ > 0 jest wtedy spełniony automatycznie.)` }; },
    () => { const t1 = pick([1, 4, 9, 16]), t2 = pick([-1, -4, -9, 2, 25]); const b = -(t1 + t2), c = t1 * t2; const roots = [t1, t2].filter((t) => t > 0).length * 2 + [t1, t2].filter((t) => t === 0).length; return { q: "Ile rozwiązań rzeczywistych ma to równanie dwukwadratowe?", expr: `x⁴ ${b > 0 ? "+ " + b : "− " + Math.abs(b)}x² ${c >= 0 ? "+ " + c : "− " + Math.abs(c)} = 0`, type: "input", ans: roots, sol: `Podstawiamy t = x², t ≥ 0: t² ${b > 0 ? "+ " + b : "− " + Math.abs(b)}t ${c >= 0 ? "+ " + c : "− " + Math.abs(c)} = 0 ⇒ t = ${M(t1)} lub t = ${M(t2)}.\nTylko dodatnie t dają rozwiązania (po dwa: ±√t). Odrzucamy t < 0.\nRazem: ${roots} rozwiązania(-ń).` }; },
    () => { const r = pick([1, 2, 3, 4, 5]), t1 = r * r, t2 = pick([-1, -4, -9]); const b = -(t1 + t2), c = t1 * t2; return { q: "Podaj największy pierwiastek tego równania.", expr: `x⁴ ${b > 0 ? "+ " + b : "− " + Math.abs(b)}x² ${c >= 0 ? "+ " + c : "− " + Math.abs(c)} = 0`, type: "input", ans: r, sol: `t = x²: t² ${b > 0 ? "+ " + b : "− " + Math.abs(b)}t ${c >= 0 ? "+ " + c : "− " + Math.abs(c)} = 0 ⇒ t = ${t1} lub t = ${M(t2)} (odpada, bo t ≥ 0).\nx² = ${t1} ⇒ x = −${r} lub x = ${r}. Największy: ${r}.` }; },
    () => { const m0 = R(4, 6); const k = m0 * m0 - 8; const good = `m = ${m0} lub m = ${M(-m0)}`; const opts = shuffle([good, `m = ${m0}`, `m = ${M(-m0)}`, `m = ${M(k)}`]); return { q: `Dla jakich m pierwiastki równania spełniają warunek x₁² + x₂² = ${M(k)}?`, expr: `x² − mx + 4 = 0`, type: "choice", options: opts, ans: good, sol: `x₁ + x₂ = m, x₁x₂ = 4.\nx₁² + x₂² = m² − 8 = ${M(k)} ⇒ m² = ${m0 * m0} ⇒ m = ±${m0}.\nSprawdzenie: Δ = m² − 16 = ${m0 * m0 - 16} ≥ 0, więc pierwiastki są rzeczywiste.` }; },
    () => ({ q: "Dla jakich wartości m równanie ma dokładnie jedno rozwiązanie?", expr: `x² − 2mx + (m + 6) = 0`, type: "choice", options: shuffle(["m = 3 lub m = −2", "m = −3 lub m = 2", "m = 6", "m ∈ ℝ"]), ans: "m = 3 lub m = −2", sol: `Δ = 4m² − 4(m + 6) = 0 ⇒ m² − m − 6 = 0.\nΔₘ = 1 + 24 = 25, √Δₘ = 5 ⇒ m = (1 ± 5)/2 ⇒ m = 3 lub m = −2.` }),
    () => { const b = RNZ(-5, 5); return { q: "Dla jakich m funkcja przyjmuje wyłącznie wartości dodatnie?", expr: `f(x) = x² ${b > 0 ? "+ " + b : "− " + Math.abs(b)}x + m`, type: "choice", options: shuffle([`m > ${fracStr(b * b, 4)}`, `m < ${fracStr(b * b, 4)}`, `m ≥ ${fracStr(b * b, 4)}`, "m > 0"]), ans: `m > ${fracStr(b * b, 4)}`, sol: `a = 1 > 0, więc wystarczy Δ < 0:\nΔ = ${b * b} − 4m < 0 ⇒ m > ${fracStr(b * b, 4)}.` }; },
];
const STAGES = [
    { id: 1, title: "Postać ogólna i wykres", subtitle: "współczynniki, parabola, wyróżnik", demo: { a: 1, b: -2, c: -3 }, gens: G1,
        theory: [
            { t: "p", v: "Funkcją kwadratową nazywamy funkcję daną wzorem f(x) = ax² + bx + c, gdzie a ≠ 0. Dziedziną jest zbiór ℝ, a wykresem — parabola." },
            { t: "f", v: "f(x) = ax² + bx + c,  a ≠ 0" },
            { t: "h", v: "Co odczytujemy ze współczynników" },
            { t: "l", v: ["a > 0 — ramiona skierowane w górę; a < 0 — w dół.", "|a| decyduje o rozwartości: im większe |a|, tym parabola węższa.", "c to rzędna punktu przecięcia z osią OY, bo f(0) = c.", "Znak b razem ze znakiem a mówi, po której stronie osi OY leży wierzchołek (p = −b/2a)."] },
            { t: "h", v: "Wyróżnik trójmianu" }, { t: "f", v: "Δ = b² − 4ac" },
            { t: "l", v: ["Δ > 0 — dwa różne miejsca zerowe, parabola przecina oś OX w dwóch punktach.", "Δ = 0 — jedno miejsce zerowe (podwójne), parabola jest styczna do osi OX.", "Δ < 0 — brak miejsc zerowych, parabola nie ma punktów wspólnych z osią OX."] },
            { t: "n", v: "Uwaga na zadania z parametrem: zanim policzysz Δ, upewnij się, że współczynnik przy x² jest różny od zera. Inaczej funkcja przestaje być kwadratowa." },
            { t: "e", q: "Przykład", v: "Dla f(x) = 2x² − 4x − 6 mamy a = 2 > 0 (ramiona w górę), c = −6 (przecięcie z OY w punkcie (0, −6)) oraz Δ = 16 + 48 = 64 > 0, więc są dwa miejsca zerowe." },
        ] },
    { id: 2, title: "Postać kanoniczna", subtitle: "wierzchołek, przesunięcia, wartość ekstremalna", demo: { a: 1, b: -4, c: 7 }, gens: G2,
        theory: [
            { t: "p", v: "Każdą funkcję kwadratową można zapisać w postaci kanonicznej. To najwygodniejsza postać do odczytywania wierzchołka, zbioru wartości i monotoniczności." },
            { t: "f", v: "f(x) = a(x − p)² + q,  W = (p, q)" }, { t: "f", v: "p = −b/(2a),  q = −Δ/(4a) = f(p)" },
            { t: "h", v: "Jak z tego korzystać" },
            { t: "l", v: ["Wykres f(x) = a(x − p)² + q to wykres y = ax² przesunięty o wektor [p, q].", "Dla a > 0 wartość najmniejsza wynosi q; dla a < 0 wartość największa wynosi q.", "Oś symetrii paraboli ma równanie x = p.", "Zbiór wartości: ⟨q, +∞) dla a > 0 oraz (−∞, q⟩ dla a < 0.", "Monotoniczność: dla a > 0 funkcja maleje na (−∞, p⟩ i rośnie na ⟨p, +∞); dla a < 0 odwrotnie."] },
            { t: "h", v: "Przejście ogólna → kanoniczna" }, { t: "e", q: "Przykład", v: "f(x) = x² − 4x + 7. Liczymy p = 4/2 = 2, q = f(2) = 4 − 8 + 7 = 3. Zatem f(x) = (x − 2)² + 3, wierzchołek W = (2, 3), wartość najmniejsza 3, ZW = ⟨3, +∞)." },
            { t: "n", v: "Znak w nawiasie jest odwrotny do współrzędnej p. Zapis (x + 5)² oznacza p = −5, nie p = 5." },
        ] },
    { id: 3, title: "Miejsca zerowe i postać iloczynowa", subtitle: "wzory na pierwiastki, rozkład na czynniki", demo: { a: 1, b: -1, c: -6 }, gens: G3,
        theory: [
            { t: "p", v: "Miejsca zerowe to rozwiązania równania ax² + bx + c = 0. Ich liczba zależy od znaku wyróżnika." },
            { t: "f", v: "x₁ = (−b − √Δ)/(2a),  x₂ = (−b + √Δ)/(2a)" }, { t: "f", v: "Δ = 0 ⇒ x₀ = −b/(2a)" },
            { t: "h", v: "Postać iloczynowa" },
            { t: "l", v: ["Gdy Δ > 0: f(x) = a(x − x₁)(x − x₂).", "Gdy Δ = 0: f(x) = a(x − x₀)².", "Gdy Δ < 0: postaci iloczynowej nie ma — trójmian jest nierozkładalny w ℝ.", "Wierzchołek leży w połowie między pierwiastkami: p = (x₁ + x₂)/2."] },
            { t: "h", v: "Równania niezupełne — licz szybciej" },
            { t: "l", v: ["ax² + bx = 0 ⇒ x(ax + b) = 0 ⇒ x = 0 lub x = −b/a.", "ax² + c = 0 ⇒ x² = −c/a — rozwiązania istnieją tylko wtedy, gdy −c/a ≥ 0.", "Gdy widzisz łatwy rozkład (np. x² − x − 6), sprawdź wzory Viète'a zamiast liczyć Δ."] },
            { t: "e", q: "Przykład", v: "x² − x − 6 = 0: Δ = 1 + 24 = 25, √Δ = 5, więc x₁ = (1 − 5)/2 = −2, x₂ = (1 + 5)/2 = 3. Stąd f(x) = (x + 2)(x − 3)." },
        ] },
    { id: 4, title: "Wzory Viète'a", subtitle: "suma i iloczyn pierwiastków, wyrażenia symetryczne", demo: { a: 1, b: -5, c: 6 }, gens: G4,
        theory: [
            { t: "p", v: "Wzory Viète'a wiążą pierwiastki równania z jego współczynnikami. Pozwalają liczyć wyrażenia symetryczne bez wyznaczania samych pierwiastków — to podstawowe narzędzie w zadaniach z parametrem." },
            { t: "f", v: "x₁ + x₂ = −b/a,  x₁ · x₂ = c/a" }, { t: "h", v: "Najczęściej używane przekształcenia" },
            { t: "l", v: ["x₁² + x₂² = (x₁ + x₂)² − 2x₁x₂", "1/x₁ + 1/x₂ = (x₁ + x₂)/(x₁x₂)", "(x₁ − x₂)² = (x₁ + x₂)² − 4x₁x₂ = Δ/a²", "x₁³ + x₂³ = (x₁ + x₂)³ − 3x₁x₂(x₁ + x₂)"] },
            { t: "h", v: "Znaki pierwiastków" }, { t: "l", v: ["Różne znaki ⇔ x₁x₂ < 0 (wtedy Δ > 0 jest automatyczne).", "Oba dodatnie ⇔ Δ > 0, x₁x₂ > 0, x₁ + x₂ > 0.", "Oba ujemne ⇔ Δ > 0, x₁x₂ > 0, x₁ + x₂ < 0."] },
            { t: "n", v: "Zanim użyjesz wzorów Viète'a w zadaniu z parametrem, zapisz warunek istnienia pierwiastków (Δ > 0 albo Δ ≥ 0). Pominięcie go to najczęstszy powód utraty punktów na maturze rozszerzonej." },
            { t: "e", q: "Przykład", v: "Dla x² − 5x + 6 = 0 mamy x₁ + x₂ = 5 i x₁x₂ = 6, więc x₁² + x₂² = 25 − 12 = 13." },
        ] },
    { id: 5, title: "Nierówności kwadratowe", subtitle: "zbiory rozwiązań, dziedziny", demo: { a: 1, b: -2, c: -8 }, gens: G5,
        theory: [
            { t: "p", v: "Nierówność kwadratową rozwiązujemy graficznie: znajdujemy miejsca zerowe, szkicujemy parabolę i odczytujemy, gdzie leży nad lub pod osią OX." },
            { t: "h", v: "Schemat postępowania" }, { t: "l", v: ["Sprowadź nierówność do postaci ax² + bx + c ≳ 0 (zero po prawej stronie).", "Policz Δ i miejsca zerowe.", "Naszkicuj parabolę — kierunek ramion wyznacza znak a.", "Odczytaj przedziały i zdecyduj o nawiasach: nierówność ostra → nawias okrągły, nieostra → domknięcie przedziału."] },
            { t: "h", v: "Przypadki graniczne" }, { t: "l", v: ["Δ < 0 i a > 0: wyrażenie jest zawsze dodatnie ⇒ > 0 daje ℝ, < 0 daje ∅.", "Δ = 0 i a > 0: ≥ 0 daje ℝ, > 0 daje ℝ bez punktu x₀, < 0 daje ∅.", "Mnożąc nierówność przez liczbę ujemną, odwracasz jej znak."] },
            { t: "n", v: "Dziedzina funkcji z pierwiastkiem √(ax² + bx + c) to zbiór, dla którego wyrażenie pod pierwiastkiem jest nieujemne — czyli nierówność nieostra, z końcami przedziałów." },
            { t: "e", q: "Przykład", v: "x² − 2x − 8 > 0: miejsca zerowe −2 i 4, a = 1 > 0, więc parabola jest nad osią poza pierwiastkami: x ∈ (−∞, −2) ∪ (4, +∞)." },
        ] },
    { id: 6, title: "Zbiór wartości i optymalizacja", subtitle: "wartości ekstremalne w przedziale, zadania tekstowe", demo: { a: -1, b: 6, c: -5 }, gens: G6,
        theory: [
            { t: "p", v: "Na poziomie rozszerzonym funkcja kwadratowa najczęściej pojawia się jako narzędzie do znajdowania wartości największej lub najmniejszej." },
            { t: "h", v: "Wartości ekstremalne w przedziale ⟨m, n⟩" }, { t: "l", v: ["Jeśli p ∈ ⟨m, n⟩, porównaj trzy wartości: f(m), f(n) oraz q = f(p).", "Jeśli p ∉ ⟨m, n⟩, funkcja jest w tym przedziale monotoniczna — wystarczą końce f(m) i f(n).", "Zawsze najpierw sprawdź położenie wierzchołka względem przedziału."] },
            { t: "h", v: "Schemat zadania optymalizacyjnego" }, { t: "l", v: ["Wprowadź zmienną x i zapisz warunki zadania (np. obwód, sumę).", "Wyraź pozostałe wielkości przez x i zapisz funkcję celu.", "Ustal dziedzinę wynikającą z treści zadania (najczęściej przedział otwarty).", "Znajdź wierzchołek i sprawdź, czy należy do dziedziny."] },
            { t: "e", q: "Przykład", v: "Prostokąt o obwodzie 20: bok b = 10 − a, pole P(a) = a(10 − a) = −a² + 10a. Wierzchołek dla a = 5, więc Pₘₐₓ = 25 — największe pole ma kwadrat." },
            { t: "n", v: "W zadaniach tekstowych dziedzina prawie nigdy nie jest całym ℝ. Pominięcie warunku typu a > 0 to typowy błąd." },
        ] },
    { id: 7, title: "Parametr i równania sprowadzalne", subtitle: "warunki na Δ, równania dwukwadratowe", demo: { a: 1, b: 0, c: -4 }, gens: G7,
        theory: [
            { t: "p", v: "Ostatni etap łączy wszystko: wyróżnik, wzory Viète'a i analizę warunków. To materiał z zadań za 4–6 punktów na maturze rozszerzonej." },
            { t: "h", v: "Typowe warunki na parametr" }, { t: "l", v: ["Dwa różne pierwiastki: a ≠ 0 i Δ > 0.", "Dokładnie jeden pierwiastek: a ≠ 0 i Δ = 0 (albo a = 0 i b ≠ 0 — przypadek liniowy!).", "Brak pierwiastków: a ≠ 0 i Δ < 0.", "Funkcja przyjmuje tylko wartości dodatnie: a > 0 i Δ < 0.", "Pierwiastki różnych znaków: c/a < 0.", "Oba pierwiastki większe od k: Δ > 0, p > k oraz a·f(k) > 0."] },
            { t: "h", v: "Równania dwukwadratowe" }, { t: "f", v: "ax⁴ + bx² + c = 0,  t = x² ≥ 0" }, { t: "l", v: ["Po podstawieniu rozwiązujemy at² + bt + c = 0.", "Każde t > 0 daje dwa rozwiązania x = ±√t.", "t = 0 daje jedno rozwiązanie x = 0.", "t < 0 odrzucamy — nie daje żadnego rozwiązania rzeczywistego."] },
            { t: "n", v: "Przy zadaniach typu x₁² + x₂² = k zawsze zapisz układ: warunek istnienia pierwiastków rzeczywistych ORAZ przekształcone wyrażenie Viète'a. Rozwiązania parametru sprzeczne z warunkiem Δ ≥ 0 trzeba odrzucić." },
            { t: "e", q: "Przykład", v: "x⁴ − 3x² − 4 = 0: t² − 3t − 4 = 0 ⇒ t = 4 lub t = −1. Odrzucamy t = −1, zostaje x² = 4, więc x = −2 lub x = 2 — dwa rozwiązania." },
        ] },
];
