const progressStore = {
    async get(key) {
        try { if (window.storage && typeof window.storage.get === 'function') return await window.storage.get(key); } catch (_) {}
        try { const value = localStorage.getItem(key); return value == null ? null : { value }; } catch (_) { return null; }
    },
    async set(key, value) {
        try { if (window.storage && typeof window.storage.set === 'function') return await window.storage.set(key, value); } catch (_) {}
        try { localStorage.setItem(key, value); } catch (_) {}
    }
};
function App() {
    const [unlocked, setUnlocked] = useState(1), [stageIdx, setStageIdx] = useState(0), [tab, setTab] = useState('teoria'), [passed, setPassed] = useState([]), [toast, setToast] = useState('');
    useEffect(() => { (async () => { const r = await progressStore.get('kwadratowa:progres'); if (r && r.value) { try { const s = JSON.parse(r.value); if (Number.isInteger(s.unlocked)) setUnlocked(Math.max(1, Math.min(s.unlocked, STAGES.length))); if (Array.isArray(s.passed)) setPassed(s.passed.filter(id => STAGES.some(st => st.id === id))); } catch (_) {} } })(); }, []);
    const save = (u, p) => progressStore.set('kwadratowa:progres', JSON.stringify({ unlocked: u, passed: p }));
    const stage = STAGES[stageIdx];
    const handlePass = () => { const p = passed.includes(stage.id) ? passed : [...passed, stage.id]; const u = Math.max(unlocked, Math.min(stage.id + 1, STAGES.length)); setPassed(p); if (u > unlocked) { setUnlocked(u); setToast(`Etap ${stage.id} zaliczony — odblokowano etap ${u}`); setTimeout(() => setToast(''), 4000); } save(u, p); };
    return React.createElement("div", { className: "min-h-screen bg-slate-50 text-slate-900" },
        React.createElement("header", { className: "bg-violet-950 text-white px-4 pt-5 pb-4" }, React.createElement("p", { className: "text-violet-300 text-xs uppercase tracking-widest" }, "Matematyka · poziom rozszerzony"), React.createElement("h1", { className: "font-serif text-2xl mt-1" }, "Funkcja i równanie kwadratowe"), React.createElement("p", { className: "text-violet-200 text-sm mt-1" }, "Siedem etapów. Każdy kończy quiz z losowanymi zadaniami — 100% otwiera następny."), React.createElement("div", { className: "mt-3 flex items-center gap-1.5" }, STAGES.map(s => React.createElement("div", { key: s.id, className: `h-1 flex-1 rounded-full ${passed.includes(s.id) ? 'bg-amber-400' : s.id <= unlocked ? 'bg-violet-600' : 'bg-violet-900'}` })))),
        React.createElement("nav", { className: "bg-white border-b border-slate-200 overflow-x-auto" }, React.createElement("div", { className: "flex gap-2 px-3 py-3 min-w-max" }, STAGES.map((s, i) => { const locked = s.id > unlocked, active = i === stageIdx; return React.createElement("button", { key: s.id, disabled: locked, onClick: () => { setStageIdx(i); setTab('teoria'); }, className: `px-3 py-2 rounded-lg text-sm whitespace-nowrap border transition-colors focus:outline-none focus:ring-2 focus:ring-violet-400 ${active ? 'bg-violet-900 text-white border-violet-900' : locked ? 'bg-slate-50 text-slate-400 border-slate-200' : 'bg-white text-slate-700 border-slate-300 hover:border-violet-400'}` }, React.createElement("span", { className: "tabular-nums opacity-70 mr-1.5" }, s.id), locked ? 'zablokowany' : s.title, passed.includes(s.id) && React.createElement("span", { className: "ml-1.5 text-amber-500" }, "✓")); }))),
        React.createElement("main", { className: "px-4 py-5 max-w-2xl mx-auto pb-16" }, React.createElement("div", { className: "mb-4" }, React.createElement("h2", { className: "font-serif text-xl text-slate-900" }, "Etap ", stage.id, ". ", stage.title), React.createElement("p", { className: "text-sm text-slate-500" }, stage.subtitle)), React.createElement("div", { className: "flex gap-1 p-1 bg-slate-200 rounded-lg mb-5" }, ['teoria', 'quiz'].map(t => React.createElement("button", { key: t, onClick: () => setTab(t), className: `flex-1 py-2 rounded-md text-sm font-medium focus:outline-none focus:ring-2 focus:ring-violet-400 ${tab === t ? 'bg-white text-violet-900 shadow-sm' : 'text-slate-600'}` }, t === 'teoria' ? 'Teoria' : 'Quiz (wymagane 100%)'))), tab === 'teoria' ? React.createElement(React.Fragment, null, React.createElement(Theory, { stage }), React.createElement("button", { onClick: () => setTab('quiz'), className: "w-full mt-6 px-6 py-3 rounded-lg bg-violet-900 text-white font-medium hover:bg-violet-800 focus:outline-none focus:ring-2 focus:ring-violet-400 focus:ring-offset-2" }, "Przejdź do quizu")) : React.createElement(Quiz, { key: stage.id, stage, onPass: handlePass })),
        toast && React.createElement("div", { className: "fixed bottom-4 left-4 right-4 mx-auto max-w-md bg-emerald-700 text-white px-4 py-3 rounded-lg text-sm text-center shadow-lg" }, toast));
}
ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App, null));
