import type { GeneratedQuestion } from "./stage1";
import { Generator, M, par, quad, fracStr, mkRoots, RNZ, pick, shuffle } from "./shared";

const G4: Generator[] = [
  () => { const {a,b,c}=mkRoots(); return { key:"stage4.sum", q:"Nie rozwiązując równania, oblicz sumę jego pierwiastków (ułamek np. 3/2).", expr:`${quad(a,b,c)} = 0`, type:"input", ans:-b/a, skill:"viete-suma", solution:`x₁+x₂=−b/a=${fracStr(-b,a)}.` }; },
  () => { const {a,b,c}=mkRoots(); return { key:"stage4.product", q:"Nie rozwiązując równania, oblicz iloczyn jego pierwiastków (ułamek np. 3/2).", expr:`${quad(a,b,c)} = 0`, type:"input", ans:c/a, skill:"viete-iloczyn", solution:`x₁x₂=c/a=${fracStr(c,a)}.` }; },
  () => { let x1=RNZ(-5,5),x2=RNZ(-5,5); while(x1===x2)x2=RNZ(-5,5); const b=-(x1+x2),c=x1*x2,S=-b,P=c,ans=S*S-2*P; return { key:"stage4.squares", q:"Oblicz x₁² + x₂², gdzie x₁, x₂ są pierwiastkami równania.", expr:`${quad(1,b,c)} = 0`, type:"input", ans, skill:"viete-wyrazenia", solution:`x₁²+x₂²=(x₁+x₂)²−2x₁x₂=${par(S)}²−2·${par(P)}=${M(ans)}.` }; },
  () => { let x1=RNZ(-5,5),x2=RNZ(-5,5); while(x1===x2 || x1*x2===0)x2=RNZ(-5,5); const b=-(x1+x2),c=x1*x2; return { key:"stage4.reciprocals", q:"Oblicz 1/x₁ + 1/x₂ (ułamek np. 3/2).", expr:`${quad(1,b,c)} = 0`, type:"input", ans:(-b)/c, skill:"viete-odwrotnosci", solution:`1/x₁+1/x₂=(x₁+x₂)/(x₁x₂)=${fracStr(-b,c)}.` }; },
  () => { const k=pick([2,3,4]),t=RNZ(-4,4),target=-(k*t+1); return { key:"stage4.parameter-sum", q:`Dla jakiej wartości m suma pierwiastków jest równa ${M(target)}?`, expr:`x² + (${k}m + 1)x − 7 = 0`, type:"input", ans:t, skill:"viete-parametr", solution:`x₁+x₂=−(${k}m+1). Z warunku otrzymujemy m=${M(t)}.` }; },
  () => { let x1=RNZ(-5,5),x2=RNZ(-5,5); while(x1===x2)x2=RNZ(-5,5); const b=-(x1+x2),c=x1*x2,ans=c<0?"różne znaki":x1>0?"oba dodatnie":"oba ujemne"; return { key:"stage4.signs", q:"Bez rozwiązywania równania określ znaki jego pierwiastków.", expr:`${quad(1,b,c)} = 0`, type:"choice", options:["oba dodatnie","oba ujemne","różne znaki"], ans, skill:"viete-znaki", solution:c<0?`x₁x₂=${M(c)}<0, więc pierwiastki mają różne znaki.`:`x₁x₂=${M(c)}>0 i x₁+x₂=${M(-b)}, więc ${ans}.` }; },
  () => { let x1=RNZ(-4,4),x2=RNZ(-4,4); while(x1===x2)x2=RNZ(-4,4); const b=-(x1+x2),c=x1*x2,val=Math.abs(x1-x2); return { key:"stage4.distance", q:"Oblicz |x₁ − x₂| dla pierwiastków równania.", expr:`${quad(1,b,c)} = 0`, type:"input", ans:val, skill:"viete-roznica", solution:`(x₁−x₂)²=(x₁+x₂)²−4x₁x₂=${val*val}, więc |x₁−x₂|=${val}.` }; },
];
export function buildStage4Quiz(count=6): GeneratedQuestion[]{ return shuffle(G4).slice(0,Math.min(count,G4.length)).map(g=>g()); }
