import type { GeneratedQuestion } from "./stage1";
import { Generator, M, quad, factored, fracStr, mkRoots, mkRootsD, RNZ, R, pick, shuffle } from "./shared";

const G3: Generator[] = [
  () => { const { a, x1, x2, b, c } = mkRoots(); const d = b*b - 4*a*c; return { key: "stage3.smaller-root", q: "Rozwiąż równanie i podaj mniejszy pierwiastek.", expr: `${quad(a,b,c)} = 0`, type: "input", ans: x1, skill: "pierwiastki-delta", solution: `Δ = ${M(d)}, √Δ = ${Math.sqrt(d)}. Pierwiastki: ${M(x1)} i ${M(x2)}. Mniejszy: ${M(x1)}.` }; },
  () => { const { a, x1, x2, b, c } = mkRootsD(); const good = factored(a,x1,x2); return { key: "stage3.factored", q: "Wskaż postać iloczynową tego trójmianu.", expr: `f(x) = ${quad(a,b,c)}`, type: "choice", options: shuffle([good, factored(a,-x1,-x2), factored(a,x1,-x2), factored(-a,x1,x2)]), ans: good, skill: "postac-iloczynowa", solution: `Miejsca zerowe: ${M(x1)} i ${M(x2)}. Zatem f(x) = ${good}.` }; },
  () => { const a = RNZ(-3,3), r = RNZ(-5,5); const b=-2*a*r,c=a*r*r; return { key: "stage3.double-root", q: "Rozwiąż równanie i podaj jego jedyne rozwiązanie.", expr: `${quad(a,b,c)} = 0`, type: "input", ans:r, skill:"pierwiastek-podwojny", solution:`Δ = 0, więc x₀ = −b/(2a) = ${M(r)}.` }; },
  () => { let a:number,b:number,c:number,d:number; do { a=RNZ(-3,3); b=R(-5,5); c=R(-6,6); d=b*b-4*a*c; } while(d>=0); return { key:"stage3.no-roots", q:"Podaj zbiór rozwiązań równania.", expr:`${quad(a,b,c)} = 0`, type:"choice", options:["∅ (brak rozwiązań)","ℝ (każda liczba)","jedno rozwiązanie","dwa rozwiązania"], ans:"∅ (brak rozwiązań)", skill:"brak-pierwiastkow", solution:`Δ = ${M(d)} < 0, więc równanie nie ma rozwiązań rzeczywistych.` }; },
  () => { const a=RNZ(-3,3); let x1=R(-5,5),x2=R(-5,5); while(x1===x2 || (x1+x2)%2!==0){x1=R(-5,5);x2=R(-5,5);} const lo=Math.min(x1,x2),hi=Math.max(x1,x2),p=(lo+hi)/2; return { key:"stage3.vertex-from-roots", q:"Odczytaj z postaci iloczynowej pierwszą współrzędną wierzchołka.", expr:`f(x) = ${factored(a,lo,hi)}`, type:"input", ans:p, skill:"wierzcholek-z-pierwiastkow", solution:`p = (x₁+x₂)/2 = (${M(lo)}+${M(hi)})/2 = ${M(p)}.` }; },
  () => { const a=RNZ(-4,4),b=RNZ(-8,8),r=-b/a; return { key:"stage3.incomplete-linear-factor", q:"Rozwiąż równanie niezupełne i podaj niezerowe rozwiązanie (ułamek np. 3/2).", expr:`${quad(a,b,0)} = 0`, type:"input", ans:r, skill:"rownanie-niezupelne", solution:`x(ax+b)=0, więc x=0 lub x=−b/a=${fracStr(-b,a)}.` }; },
  () => { const a=pick([1,2,3,4]),k=pick([1,4,9,16,25]),c=-a*k,r=Math.sqrt(k); return { key:"stage3.incomplete-square", q:"Rozwiąż równanie i podaj większy pierwiastek.", expr:`${quad(a,0,c)} = 0`, type:"input", ans:r, skill:"rownanie-ax2-c", solution:`x²=${k}, więc x=−${r} lub x=${r}. Większy pierwiastek: ${r}.` }; },
];
export function buildStage3Quiz(count=6): GeneratedQuestion[]{ return shuffle(G3).slice(0,Math.min(count,G3.length)).map(g=>g()); }
