import type { GeneratedQuestion } from "./stage1";
import { Generator, M, fracStr, RNZ, pick, shuffle, uniq } from "./shared";

const G7: Generator[] = [
  () => { const b=2*RNZ(-4,4),bound=(b*b)/4,good=`m < ${M(bound)}`; return { key:"stage7.two-roots", q:"Dla jakich wartości m równanie ma dwa różne pierwiastki rzeczywiste?", expr:`x² ${b>0?"+ "+b:"− "+Math.abs(b)}x + m = 0`, type:"choice", options:shuffle([good,`m > ${M(bound)}`,`m ≤ ${M(bound)}`,`m = ${M(bound)}`]), ans:good, skill:"parametr-delta-dodatnia", solution:`Δ=${b*b}−4m>0, więc ${good}.` }; },
  () => { const b=RNZ(-6,6),k=RNZ(-6,6),good=`m < ${M(-k)}`; return { key:"stage7.opposite-signs", q:"Dla jakich m równanie ma dwa pierwiastki o różnych znakach?", expr:`x² ${b>0?"+ "+b:"− "+Math.abs(b)}x + (m ${k>=0?"+ "+k:"− "+Math.abs(k)}) = 0`, type:"choice", options:shuffle(uniq([good,`m > ${M(-k)}`,`m < ${M(k)}`,`m > ${M(k)}`])), ans:good, skill:"parametr-znaki-pierwiastkow", solution:`Różne znaki ⇔ x₁x₂<0, więc ${good}.` }; },
  () => { const t1=pick([1,4,9,16]),t2=pick([-1,-4,-9,2,25]),b=-(t1+t2),c=t1*t2,roots=[t1,t2].filter(t=>t>0).length*2+[t1,t2].filter(t=>t===0).length; return { key:"stage7.biquadratic-count", q:"Ile rozwiązań rzeczywistych ma to równanie dwukwadratowe?", expr:`x⁴ ${b>0?"+ "+b:"− "+Math.abs(b)}x² ${c>=0?"+ "+c:"− "+Math.abs(c)} = 0`, type:"input", ans:roots, skill:"rownanie-dwukwadratowe", solution:`Po podstawieniu t=x² otrzymujemy t=${M(t1)} lub t=${M(t2)}. Każde t>0 daje dwa rozwiązania, t<0 żadnego. Razem: ${roots}.` }; },
  () => { const r=pick([1,2,3,4,5]),t1=r*r,t2=pick([-1,-4,-9]),b=-(t1+t2),c=t1*t2; return { key:"stage7.biquadratic-largest", q:"Podaj największy pierwiastek tego równania.", expr:`x⁴ ${b>0?"+ "+b:"− "+Math.abs(b)}x² ${c>=0?"+ "+c:"− "+Math.abs(c)} = 0`, type:"input", ans:r, skill:"dwukwadratowe-pierwiastki", solution:`t=x² daje t=${t1} lub ${M(t2)}. Ujemne t odrzucamy, więc x=±${r}. Największy: ${r}.` }; },
  () => { const m0=pick([5,6]),k=m0*m0-8,good=`m = ${m0} lub m = ${M(-m0)}`; return { key:"stage7.viete-parameter", q:`Dla jakich m pierwiastki równania spełniają x₁² + x₂² = ${M(k)}?`, expr:"x² − mx + 4 = 0", type:"choice", options:shuffle([good,`m = ${m0}`,`m = ${M(-m0)}`,`m = ${M(k)}`]), ans:good, skill:"parametr-viete", solution:`x₁+x₂=m, x₁x₂=4, więc x₁²+x₂²=m²−8=${M(k)}. Stąd m=±${m0}; dla obu wartości Δ=m²−16>0.` }; },
  () => ({ key:"stage7.one-root", q:"Dla jakich wartości m równanie ma dokładnie jedno rozwiązanie?", expr:"x² − 2mx + (m + 6) = 0", type:"choice", options:shuffle(["m = 3 lub m = −2","m = −3 lub m = 2","m = 6","m ∈ ℝ"]), ans:"m = 3 lub m = −2", skill:"parametr-delta-zero", solution:"Δ=4m²−4(m+6)=0, czyli m²−m−6=0. Stąd m=3 lub m=−2." }),
  () => { const b=RNZ(-5,5),bound=fracStr(b*b,4),ans=`m > ${bound}`; return { key:"stage7.always-positive", q:"Dla jakich m funkcja przyjmuje wyłącznie wartości dodatnie?", expr:`f(x) = x² ${b>0?"+ "+b:"− "+Math.abs(b)}x + m`, type:"choice", options:shuffle([ans,`m < ${bound}`,`m ≥ ${bound}`,"m > 0"]), ans, skill:"parametr-dodatnia-funkcja", solution:`a=1>0 i funkcja ma być zawsze dodatnia, więc Δ<0: ${b*b}−4m<0, czyli ${ans}.` }; },
];
export function buildStage7Quiz(count=6): GeneratedQuestion[]{ return shuffle(G7).slice(0,Math.min(count,G7.length)).map(g=>g()); }
