import type { GeneratedQuestion } from "./stage1";
import { Generator, M, quad, mkRoots, RNZ, R, pick, shuffle, uniq, ivOpen, ivClosed, ivOutOpen, ivOutClosed } from "./shared";

const G5: Generator[] = [
  () => { const {a,x1,x2,b,c}=mkRoots(); const strict=Math.random()<0.5,sign=pick([">","<"]),up=a>0,outside=(sign===">")===up; const good=outside?(strict?ivOutOpen(x1,x2):ivOutClosed(x1,x2)):(strict?ivOpen(x1,x2):ivClosed(x1,x2)); const symbol=strict?sign:sign===">"?"≥":"≤"; return { key:"stage5.standard", q:"Rozwiąż nierówność.", expr:`${quad(a,b,c)} ${symbol} 0`, type:"choice", options:shuffle([ivOpen(x1,x2),ivClosed(x1,x2),ivOutOpen(x1,x2),ivOutClosed(x1,x2)]), ans:good, skill:"nierownosc-przedzialy", solution:`Miejsca zerowe: ${M(x1)} i ${M(x2)}, ramiona ${up?"w górę":"w dół"}. Odpowiedź: ${good}.` }; },
  () => { let a:number,b:number,c:number,d:number; do{a=RNZ(-3,3);b=R(-5,5);c=R(-6,6);d=b*b-4*a*c;}while(d>=0); const sign=pick([">","<"]),always=(sign===">")===(a>0),ans=always?"x ∈ ℝ":"∅ (brak rozwiązań)"; return { key:"stage5.no-roots", q:"Rozwiąż nierówność.", expr:`${quad(a,b,c)} ${sign} 0`, type:"choice", options:["x ∈ ℝ","∅ (brak rozwiązań)","x ∈ (0, +∞)","x ∈ (−∞, 0)"], ans, skill:"nierownosc-delta-ujemna", solution:`Δ=${M(d)}<0, więc trójmian ma stały znak zgodny z a. Odpowiedź: ${ans}.` }; },
  () => { const x1=R(-5,3),x2=x1+R(2,6),b=-(x1+x2),c=x1*x2,count=x2-x1-1; return { key:"stage5.integers", q:"Ile liczb całkowitych spełnia tę nierówność?", expr:`${quad(1,b,c)} < 0`, type:"input", ans:count, skill:"nierownosc-liczby-calkowite", solution:`Rozwiązaniem jest (${M(x1)}, ${M(x2)}). Liczb całkowitych ostro między końcami jest ${count}.` }; },
  () => { const {x1,x2}=mkRoots(); const A=RNZ(1,4),bb=-A*(x1+x2),cc=A*x1*x2,good=ivOutClosed(x1,x2); return { key:"stage5.sqrt-domain", q:"Wyznacz dziedzinę funkcji.", expr:`g(x) = √(${quad(A,bb,cc)})`, type:"choice", options:shuffle(uniq([good,ivClosed(x1,x2),ivOutOpen(x1,x2),"x ∈ ℝ"])), ans:good, skill:"dziedzina-pierwiastek", solution:`Pod pierwiastkiem musi być ≥0. Dla a>0 otrzymujemy ${good}.` }; },
  () => { const r=RNZ(-4,4),b=-2*r,c=r*r,sign=pick(["≥",">"]),ans=sign==="≥"?"x ∈ ℝ":`x ∈ ℝ \\ {${M(r)}}`; return { key:"stage5.double-root", q:"Rozwiąż nierówność.", expr:`${quad(1,b,c)} ${sign} 0`, type:"choice", options:shuffle(["x ∈ ℝ",`x ∈ ℝ \\ {${M(r)}}`,`x = ${M(r)}`,"∅ (brak rozwiązań)"]), ans, skill:"nierownosc-pierwiastek-podwojny", solution:`(x ${r>0?"− "+r:"+ "+Math.abs(r)})² jest zawsze nieujemne. Odpowiedź: ${ans}.` }; },
  () => { const x1=R(-5,2),x2=x1+R(2,5),b=-(x1+x2),c=x1*x2,k=R(x1+1,x2-1); return { key:"stage5.test-number", q:`Czy liczba ${M(k)} spełnia nierówność? Wpisz 1 (tak) lub 0 (nie).`, expr:`${quad(1,b,c)} > 0`, type:"input", ans:0, skill:"nierownosc-sprawdzenie", solution:`${M(k)} leży między miejscami zerowymi ${M(x1)} i ${M(x2)}, gdzie trójmian jest ujemny. Odpowiedź: 0.` }; },
];
export function buildStage5Quiz(count=6): GeneratedQuestion[]{ return shuffle(G5).slice(0,Math.min(count,G5.length)).map(g=>g()); }
