import type { GeneratedQuestion } from "./stage1";
import { Generator, M, quad, mkPQ, mkPQd, RNZ, R, shuffle, uniq } from "./shared";

const G6: Generator[] = [
  () => { const {a,p,q,b,c}=mkPQd(); const good=a>0?`⟨${M(q)}, +∞)`:`(−∞, ${M(q)}⟩`; return { key:"stage6.range", q:"Wyznacz zbiór wartości funkcji.", expr:`f(x) = ${quad(a,b,c)}`, type:"choice", options:shuffle(uniq([`⟨${M(q)}, +∞)`,`(−∞, ${M(q)}⟩`,`⟨${M(p)}, +∞)`,"ℝ"])), ans:good, skill:"zbior-wartosci", solution:`Wierzchołek to (${M(p)}, ${M(q)}), więc zbiór wartości to ${good}.` }; },
  () => { const {a,p,q,b,c}=mkPQd(); const good=a>0?`⟨${M(p)}, +∞)`:`(−∞, ${M(p)}⟩`; return { key:"stage6.increasing", q:"W jakim przedziale funkcja jest rosnąca?", expr:`f(x) = ${quad(a,b,c)}`, type:"choice", options:shuffle(uniq([`⟨${M(p)}, +∞)`,`(−∞, ${M(p)}⟩`,`⟨${M(q)}, +∞)`,`(−∞, ${M(q)}⟩`])), ans:good, skill:"monotonicznosc", solution:`p=${M(p)} i a=${M(a)}. Przedział wzrostu: ${good}.` }; },
  () => { const {a,p,q,b,c}=mkPQ(); const m=p-R(1,4),n=p+R(1,4),f=(x:number)=>a*x*x+b*x+c,vals=[f(m),f(n),q],wantMax=Math.random()<0.5,ans=wantMax?Math.max(...vals):Math.min(...vals); return { key:"stage6.interval-with-vertex", q:`Wyznacz ${wantMax?"największą":"najmniejszą"} wartość funkcji w przedziale ⟨${M(m)}, ${M(n)}⟩.`, expr:`f(x) = ${quad(a,b,c)}`, type:"input", ans, skill:"ekstremum-przedzial", solution:`Porównujemy f(${M(m)})=${M(f(m))}, f(${M(p)})=${M(q)} i f(${M(n)})=${M(f(n))}. Wynik: ${M(ans)}.` }; },
  () => { const {a,p,b,c}=mkPQ(); const m=p+R(1,3),n=m+R(1,4),f=(x:number)=>a*x*x+b*x+c,wantMax=Math.random()<0.5,ans=wantMax?Math.max(f(m),f(n)):Math.min(f(m),f(n)); return { key:"stage6.interval-monotonic", q:`Wyznacz ${wantMax?"największą":"najmniejszą"} wartość funkcji w przedziale ⟨${M(m)}, ${M(n)}⟩.`, expr:`f(x) = ${quad(a,b,c)}`, type:"input", ans, skill:"ekstremum-monotonicznosc", solution:`Wierzchołek x=${M(p)} nie należy do przedziału, więc porównujemy końce: ${M(f(m))} i ${M(f(n))}. Wynik: ${M(ans)}.` }; },
  () => { const half=R(3,12),L=4*half; return { key:"stage6.rectangle", q:`Obwód prostokąta wynosi ${L}. Jakie jest największe możliwe pole?`, expr:`2(a + b) = ${L}`, type:"input", ans:half*half, skill:"optymalizacja-prostokat", solution:`P(a)=a(${L/2}−a). Maksimum jest dla a=b=${half}, więc Pmax=${half*half}.` }; },
  () => { const h=R(3,14),S=2*h; return { key:"stage6.product", q:`Suma dwóch liczb rzeczywistych wynosi ${S}. Jaki jest ich największy możliwy iloczyn?`, expr:`x + y = ${S}`, type:"input", ans:h*h, skill:"optymalizacja-iloczyn", solution:`I(x)=x(${S}−x) ma maksimum dla x=y=${h}. Iloczyn maksymalny: ${h*h}.` }; },
  () => { const {a,q,b,c}=mkPQ(); const k=q+(a>0?-RNZ(1,5):RNZ(1,5)); return { key:"stage6.horizontal-line", q:`Ile rozwiązań ma równanie f(x) = ${M(k)}?`, expr:`f(x) = ${quad(a,b,c)}`, type:"input", ans:0, skill:"zbior-wartosci-rownanie", solution:`Liczba ${M(k)} nie należy do zbioru wartości tej funkcji, więc równanie ma 0 rozwiązań.` }; },
];
export function buildStage6Quiz(count=6): GeneratedQuestion[]{ return shuffle(G6).slice(0,Math.min(count,G6.length)).map(g=>g()); }
